// Auto-generated by scripts/optimize-images.mjs — do not edit.
export const portraitBlur =
  "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoQABQAPu1iqU2ppaQiMAgBMB2JZQC2yBtra4l9KwAA/ujxozaWjL1tgDRhF/DX5Rl7t7N/aktj/c/Ap1D4KNpqqEWZFA2lAAAAAA==";
