/**
 * One-shot image pipeline.
 * Cleans up + sharpens the source portraits and emits web-optimized WebP
 * assets into /public, plus a tiny base64 blur placeholder for next/image.
 *
 *   npm run optimize:images
 */
import sharp from "sharp";
import { writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const SRC_DIR = join(homedir(), "Documents/Personal/Profession_photo");
const OUT_DIR = join(process.cwd(), "public");

const HEADSHOT_SRC = join(SRC_DIR, "WhatsApp Image 2026-07-22 at 11.04.28 PM.jpeg");
// Hero now uses the studio headshot, cropped to a clean 4:5 portrait.
const HERO_SRC = HEADSHOT_SRC;
const HERO_W = 1000;
const HERO_H = 1250; // 4:5

/** Gentle "clean + crisp" pass: mild denoise (median) then unsharp mask. */
function refine(pipeline) {
  return pipeline
    .median(1) // knock back sensor noise without smearing detail
    .sharpen({ sigma: 1.1, m1: 0.6, m2: 2.2 }); // crisp edges, restrained
}

async function buildHero() {
  await refine(
    sharp(HERO_SRC)
      .rotate()
      // 4:5 crop, kept centered so the face stays framed; upscaled cleanly.
      .resize({
        width: HERO_W,
        height: HERO_H,
        fit: "cover",
        position: "centre",
        kernel: sharp.kernel.lanczos3,
        withoutEnlargement: false,
      })
  )
    .webp({ quality: 88, effort: 6, smartSubsample: true })
    .toFile(join(OUT_DIR, "portrait.webp"));

  // Small, fast blur placeholder (base64) for zero-jank loading.
  const blurBuf = await sharp(HERO_SRC)
    .rotate()
    .resize({ width: 16, height: 20, fit: "cover", position: "centre" })
    .blur(1)
    .webp({ quality: 40 })
    .toBuffer();
  const blurDataURL = `data:image/webp;base64,${blurBuf.toString("base64")}`;

  await writeFile(
    join(process.cwd(), "lib", "portrait-blur.ts"),
    `// Auto-generated by scripts/optimize-images.mjs — do not edit.\n` +
      `export const portraitBlur =\n  "${blurDataURL}";\n`
  );

  return { targetW: HERO_W };
}

async function buildHeadshot() {
  await refine(
    sharp(HEADSHOT_SRC)
      .rotate()
      .resize({ width: 640, height: 640, fit: "cover", position: "top", kernel: sharp.kernel.lanczos3 })
  )
    .webp({ quality: 88, effort: 6 })
    .toFile(join(OUT_DIR, "headshot.webp"));
}

const hero = await buildHero();
await buildHeadshot();

console.log("✓ portrait.webp   (hero, refined + upscaled to ~%dpx wide)", hero.targetW);
console.log("✓ headshot.webp   (640×640, refined)");
console.log("✓ lib/portrait-blur.ts (blur placeholder)");
